sudo: false
language: node_js
node_js: # automatically infers from .nvmrc
cache:
  yarn: true
services:
- docker
before_install:
- docker build -t lightapp .
- docker run -p 3000:3000 lightapp
- curl localhost:3000
script:
- npm run lint
- npm run test